version: '3.1'
services:
  web:
    image: benjaminrodev/agenda_sw1:3.0.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - /var/lib/odoo
      - ./config:/etc/odoo
      - /etc/odoo
      - /mnt/extra-addons
      - /var/log/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=myodoo
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-db-data: